from __future__ import annotations

from typing import Dict, Iterable, List


ERROR_CODE_UNKNOWN = "BRO-0000"

# Stable codebook for critical guard/gate findings.
ERROR_CODEBOOK: Dict[str, str] = {
    "BRO-1001": "Missing secret source value",
    "BRO-1002": "Invalid private key format",
    "BRO-1003": "Invalid funder address format",
    "BRO-1101": "Run manifest missing",
    "BRO-1102": "Run manifest invalid",
    "BRO-1103": "Run manifest stale",
    "BRO-1201": "Run integrity insufficient status rows",
    "BRO-1202": "Run integrity missing status timestamp",
    "BRO-1203": "Run integrity stale status timestamp",
    "BRO-1204": "Run integrity status counter non-monotonic",
    "BRO-1301": "Clock sync disabled",
    "BRO-1302": "Clock skew threshold invalid",
    "BRO-1303": "Clock skew threshold too loose",
    "BRO-1304": "Status timestamp non-monotonic",
    "BRO-1305": "Status timestamp missing",
    "BRO-1306": "Status timestamp stale",
    "BRO-1401": "Required network drill evidence missing",
    "BRO-1402": "Network drill evidence invalid",
    "BRO-1501": "Promotion gate uptime below threshold",
    "BRO-1502": "Promotion gate error budget exceeded",
    "BRO-1503": "Promotion gate execution quality below threshold",
    "BRO-1504": "Promotion gate reconciliation mismatch too high",
    "BRO-1601": "Live mode required but config is not live",
    "BRO-1701": "Paper/live parity gap on quote uptime",
    "BRO-1702": "Paper/live parity gap on error rows",
    "BRO-1703": "Paper/live parity gap on capture minus adverse",
    "BRO-1704": "Paper/live parity gap on sniper fill rate",
    "BRO-1705": "Paper/live parity gap on latency p90",
    "BRO-1801": "Performance gate insufficient status rows",
    "BRO-1802": "Performance gate cycle latency p95 breach",
    "BRO-1803": "Performance gate cycle latency max breach",
    "BRO-1804": "Performance gate process memory breach",
    "BRO-1805": "Performance gate order capacity ratio breach",
    "BRO-1806": "Performance gate cancel capacity ratio breach",
    "BRO-1807": "Performance gate latency inactive cycles breach",
    "BRO-1808": "Performance gate market-data span breach",
    "BRO-1809": "Performance gate strategy span breach",
    "BRO-1810": "Performance gate state I/O span breach",
    "BRO-1811": "Performance gate status I/O span breach",
    "BRO-1812": "Performance gate residual span breach",
    "BRO-1901": "Dependency reproducibility lock manifest missing/invalid",
    "BRO-1902": "Dependency requirement unpinned",
    "BRO-1903": "Dependency/build lock hash mismatch",
    "BRO-1904": "Docker reproducibility guard failed",
    "BRO-2001": "Soak hardening readiness stage below requirement",
    "BRO-2002": "Soak hardening duration below minimum",
    "BRO-2003": "Soak hardening quote uptime below minimum",
    "BRO-2004": "Soak hardening error rows above maximum",
    "BRO-2005": "Soak hardening maker/taker execution path activity below minimum",
    "BRO-2101": "Regression envelope metric breach",
    "BRO-2102": "Regression envelope missing required metric",
    "BRO-2201": "Websocket/feed reliability evidence breach",
    "BRO-2301": "API contract drift audit breach",
    "BRO-2401": "Soak evidence window insufficient runs/duration",
    "BRO-2402": "Soak evidence window pass-count criteria not met",
    "BRO-2403": "Soak delta regression beyond allowed thresholds",
    "BRO-2501": "Runtime hardening audit breach",
}


_PREFIX_CODE_RULES: List[tuple[str, str]] = [
    ("secret_load_failed:", "BRO-1001"),
    ("invalid_private_key:", "BRO-1002"),
    ("invalid_funder:", "BRO-1003"),
    ("run_manifest_missing", "BRO-1101"),
    ("run_manifest_invalid_", "BRO-1102"),
    ("run_manifest_stale_", "BRO-1103"),
    ("status_rows_below_min:", "BRO-1201"),
    ("latest_status_ts_missing", "BRO-1202"),
    ("latest_status_stale:", "BRO-1203"),
    ("status_counter_non_monotonic:", "BRO-1204"),
    ("preflight_clock_sync_disabled", "BRO-1301"),
    ("preflight_max_clock_skew_invalid", "BRO-1302"),
    ("preflight_max_clock_skew_too_loose:", "BRO-1303"),
    ("status_ts_non_monotonic_rows:", "BRO-1304"),
    ("status_ts_missing", "BRO-1305"),
    ("status_ts_too_stale:", "BRO-1306"),
    ("missing_recent_ok_drill:", "BRO-1401"),
    ("invalid_json:", "BRO-1402"),
    ("invalid_payload:", "BRO-1402"),
    ("quote_uptime_ratio_too_low:", "BRO-1501"),
    ("error_rows_too_high:", "BRO-1502"),
    ("execution_quality_net_too_low:", "BRO-1503"),
    ("soak_execution_quality_capture_minus_adverse_too_low:", "BRO-1503"),
    ("reconcile_mismatch_ratio_too_high:", "BRO-1504"),
    ("config_mode_not_live:", "BRO-1601"),
    ("parity_gap_quote_uptime:", "BRO-1701"),
    ("parity_gap_error_rows:", "BRO-1702"),
    ("parity_gap_capture_minus_adverse:", "BRO-1703"),
    ("parity_gap_sniper_fill_rate:", "BRO-1704"),
    ("parity_gap_latency_p90_ms:", "BRO-1705"),
    ("performance_status_rows_too_few:", "BRO-1801"),
    ("performance_cycle_latency_p95_too_high:", "BRO-1802"),
    ("performance_cycle_latency_max_too_high:", "BRO-1803"),
    ("performance_process_rss_too_high:", "BRO-1804"),
    ("performance_order_capacity_used_ratio_too_high:", "BRO-1805"),
    ("performance_cancel_capacity_used_ratio_too_high:", "BRO-1806"),
    ("performance_latency_inactive_cycles_too_high:", "BRO-1807"),
    ("performance_cycle_span_market_data_too_high:", "BRO-1808"),
    ("performance_cycle_span_strategy_exec_too_high:", "BRO-1809"),
    ("performance_cycle_span_state_io_too_high:", "BRO-1810"),
    ("performance_cycle_span_status_io_too_high:", "BRO-1811"),
    ("performance_cycle_span_residual_too_high:", "BRO-1812"),
    ("lock_manifest_missing:", "BRO-1901"),
    ("lock_manifest_invalid_json:", "BRO-1901"),
    ("lock_manifest_files_invalid", "BRO-1901"),
    ("pyproject_missing:", "BRO-1901"),
    ("pyproject_invalid_toml:", "BRO-1901"),
    ("pyproject_dependencies_invalid", "BRO-1901"),
    ("dependency_unpinned_requirement:", "BRO-1902"),
    ("pyproject_dependency_unpinned:", "BRO-1902"),
    ("lock_manifest_hash_mismatch:", "BRO-1903"),
    ("pyproject_dependency_missing_in_requirements:", "BRO-1903"),
    ("requirements_dependency_missing_in_pyproject:", "BRO-1903"),
    ("pyproject_dependency_version_mismatch:", "BRO-1903"),
    ("dockerfile_missing_requirements_install_step", "BRO-1904"),
    ("dockerfile_missing_from", "BRO-1904"),
    ("dockerfile_base_image_unpinned_digest", "BRO-1904"),
    ("soak_readiness_below_required_stage:", "BRO-2001"),
    ("readiness_runtime_invalid:", "BRO-2001"),
    ("readiness_runtime_non_promotable:", "BRO-2001"),
    ("soak_duration_too_short:", "BRO-2002"),
    ("soak_quote_uptime_too_low:", "BRO-2003"),
    ("soak_error_rows_too_high:", "BRO-2004"),
    ("soak_runtime_invalid:", "BRO-2001"),
    ("soak_runtime_non_promotable:", "BRO-2005"),
    ("soak_maker_submits_too_low:", "BRO-2005"),
    ("soak_taker_bonus_submits_too_low:", "BRO-2005"),
    ("soak_taker_bonus_fills_too_low:", "BRO-2005"),
    ("regression_envelope_breach:", "BRO-2101"),
    ("regression_envelope_missing_metric:", "BRO-2102"),
    ("websocket_evidence_book_feed_down_ratio_too_high:", "BRO-2201"),
    ("websocket_evidence_chainlink_down_ratio_too_high:", "BRO-2201"),
    ("websocket_evidence_book_feed_reconnects_per_hour_too_high:", "BRO-2201"),
    ("websocket_evidence_chainlink_reconnects_per_hour_too_high:", "BRO-2201"),
    ("websocket_evidence_book_feed_last_msg_age_too_high:", "BRO-2201"),
    ("websocket_evidence_chainlink_last_tick_age_too_high:", "BRO-2201"),
    ("websocket_evidence_chainlink_dropped_ticks_too_high:", "BRO-2201"),
    ("websocket_evidence_chainlink_queue_size_too_high:", "BRO-2201"),
    ("websocket_slo_status_rows_too_few:", "BRO-2201"),
    ("websocket_slo_book_feed_missing_rows:", "BRO-2201"),
    ("websocket_slo_chainlink_missing_rows:", "BRO-2201"),
    ("websocket_slo_book_feed_down_ratio_too_high:", "BRO-2201"),
    ("websocket_slo_chainlink_down_ratio_too_high:", "BRO-2201"),
    ("websocket_slo_book_feed_reconnects_per_hour_too_high:", "BRO-2201"),
    ("websocket_slo_chainlink_reconnects_per_hour_too_high:", "BRO-2201"),
    ("websocket_slo_book_feed_last_msg_age_too_high:", "BRO-2201"),
    ("websocket_slo_chainlink_last_tick_age_too_high:", "BRO-2201"),
    ("websocket_slo_chainlink_dropped_ticks_too_high:", "BRO-2201"),
    ("websocket_slo_chainlink_queue_size_too_high:", "BRO-2201"),
    ("websocket_promotion_book_feed_down_ratio_too_high:", "BRO-2201"),
    ("websocket_promotion_chainlink_down_ratio_too_high:", "BRO-2201"),
    ("websocket_promotion_book_feed_reconnects_per_hour_too_high:", "BRO-2201"),
    ("websocket_promotion_chainlink_reconnects_per_hour_too_high:", "BRO-2201"),
    ("websocket_promotion_chainlink_dropped_ticks_too_high:", "BRO-2201"),
    ("websocket_promotion_report_missing", "BRO-2201"),
    ("api_contract_missing_sample:", "BRO-2301"),
    ("api_contract_missing_field:", "BRO-2301"),
    ("api_contract_type_mismatch:", "BRO-2301"),
    ("soak_evidence_insufficient_runs:", "BRO-2401"),
    ("soak_evidence_duration_total_too_low:", "BRO-2401"),
    ("soak_evidence_recency_order_invalid", "BRO-2401"),
    ("soak_evidence_reliability_passes_too_few:", "BRO-2402"),
    ("soak_evidence_utilization_passes_too_few:", "BRO-2402"),
    ("soak_evidence_promotion_passes_too_few:", "BRO-2402"),
    ("soak_delta_", "BRO-2403"),
    ("runtime_service_", "BRO-2501"),
    ("runtime_host_", "BRO-2501"),
    ("paper_harness_runtime_invalid:", "BRO-2501"),
    ("paper_harness_runtime_non_promotable:", "BRO-2501"),
]


def code_for_finding(finding: str) -> str:
    text = str(finding or "").strip()
    if not text:
        return ERROR_CODE_UNKNOWN
    for prefix, code in _PREFIX_CODE_RULES:
        if text.startswith(prefix):
            return code
    return ERROR_CODE_UNKNOWN


def summarize_error_codes(findings: Iterable[str]) -> List[str]:
    return sorted({code_for_finding(item) for item in findings})
