"""Compatibility facade for BRO wallet doctrine.

Canonical wallet implementation now lives under ``prodesk.wallet``.
This module remains as a stable import surface for existing integrations.
"""

from .wallet import (
    AUTHORITY_CLASS_BOOTSTRAP,
    AUTHORITY_CLASS_DEPRECATED,
    AUTHORITY_CLASS_DERIVED,
    AUTHORITY_CLASS_LIVE,
    AUTHORITY_CLASS_LOCAL,
    AllowanceSnapshot,
    LiveWalletGuardian,
    LiveWalletDoctrine,
    LiveWalletTruthSource,
    NonceSnapshot,
    OpenOrderStateSnapshot,
    PaperWalletGuardian,
    PaperWalletDoctrine,
    PendingTxSnapshot,
    ReconciliationResult,
    TRUTH_DOMAIN_BOOTSTRAP_NON_AUTHORITATIVE,
    TRUTH_DOMAIN_CANONICAL_LIVE_WALLET,
    TRUTH_DOMAIN_INTEGRITY_TRIPWIRE_RECONCILE,
    TRUTH_DOMAIN_LOCAL_TX_LIFECYCLE,
    TRUTH_DOMAIN_OPEN_ORDER_STATE,
    TRUTH_DOMAIN_PAPER_WALLET,
    WalletAuthorization,
    WalletRedemptionExecutor,
    WalletRedemptionRequest,
    WalletRedemptionResult,
    WalletDoctrine,
    WalletDoctrineBase,
    WalletGuardianBase,
    WalletSnapshot,
    create_wallet_controller,
    create_wallet_doctrine,
    create_wallet_guardian,
    create_wallet_guardian_controller,
)

__all__ = [
    "AUTHORITY_CLASS_BOOTSTRAP",
    "AUTHORITY_CLASS_DEPRECATED",
    "AUTHORITY_CLASS_DERIVED",
    "AUTHORITY_CLASS_LIVE",
    "AUTHORITY_CLASS_LOCAL",
    "AllowanceSnapshot",
    "LiveWalletGuardian",
    "LiveWalletDoctrine",
    "LiveWalletTruthSource",
    "NonceSnapshot",
    "OpenOrderStateSnapshot",
    "PaperWalletGuardian",
    "PaperWalletDoctrine",
    "PendingTxSnapshot",
    "ReconciliationResult",
    "TRUTH_DOMAIN_BOOTSTRAP_NON_AUTHORITATIVE",
    "TRUTH_DOMAIN_CANONICAL_LIVE_WALLET",
    "TRUTH_DOMAIN_INTEGRITY_TRIPWIRE_RECONCILE",
    "TRUTH_DOMAIN_LOCAL_TX_LIFECYCLE",
    "TRUTH_DOMAIN_OPEN_ORDER_STATE",
    "TRUTH_DOMAIN_PAPER_WALLET",
    "WalletAuthorization",
    "WalletRedemptionExecutor",
    "WalletRedemptionRequest",
    "WalletRedemptionResult",
    "WalletDoctrine",
    "WalletDoctrineBase",
    "WalletGuardianBase",
    "WalletSnapshot",
    "create_wallet_controller",
    "create_wallet_doctrine",
    "create_wallet_guardian",
    "create_wallet_guardian_controller",
]
